---
- hosts: all
  tasks:
    - name: get file
      copy: src=/data/tools/ansible/modules/hive/package/apache-hive-1.2.1-bin.tar.gz dest=/tmp/apache-hive-1.2.1-bin.tar.gz owner=root group=root mode=0771
      tags: install

    - name: tar file to /app
      shell: cd /tmp && tar zxvf  apache-hive-1.2.1-bin.tar.gz -C /app
      tags: install
      args:
        creates: /app/apache-hive-1.2.1-bin/.install

    - name: create log directory
      file: path=/data/logs/hive12 state=directory owner=hadoop group=hadoop mode=0777
      tags: install

    - name: change owner
      file: name=/app/apache-hive-1.2.1-bin owner=hadoop group=hadoop
      tags: install

    - name: touch install file
      shell: touch /app/apache-hive-1.2.1-bin/.install
      tags: install
      args:
        creates: /app/apache-hive-1.2.1-bin/.install

    - name: copy jar file to remote host
      copy: src=/data/tools/ansible/modules/hive/config_test12/{{ item }} dest=/app/apache-hive-1.2.1-bin/lib/{{ item }} owner=hadoop group=hadoop mode=0771
      tags: config
      with_items:
          - mysql-connector-java-5.1.39-bin.jar

    - name: copy config file
      copy: src=/data/tools/ansible/modules/hive/config_test12/{{ item }} dest=/app/apache-hive-1.2.1-bin/conf/{{ item }} owner=hadoop group=hadoop mode=755
      tags: config
      with_items:
        - hive-site.xml

    - name: create Create a soft link
      file: src=/app/apache-hive-1.2.1-bin dest=/opt/hive12 state=link owner=hadoop group=hadoop
      tags: link
