---
- hosts: all
  tasks:
    - name: create user group
      group: name={{ item }} state=present
      with_items:
        - hadoop
        - moretv

    - name: add users
      user: name={{ item.name }} state=present group={{ item.groups }}
      with_items:
        - { name: 'hdfs', groups: 'hadoop' }
        - { name: 'yarn', groups: 'hadoop' }
        - { name: 'mesos', groups: 'hadoop' }
        - { name: 'hadoop', groups: 'hadoop' }
        - { name: 'moretv', groups: 'moretv' }
        - { name: 'spark', groups: 'hadoop' }
        - { name: 'storm', groups: 'hadoop' }

    - name: create directory
      file: path={{ item.name }} state=directory owner={{ item.user }} group={{ item.groups }}   
      with_items: 
        - { name: '/opt', user: 'root', groups: 'root' }
        - { name: '/app', user: 'root', groups: 'root' }
        - { name: '/data/logs', user: 'root', groups: 'root' }
        - { name: '/data/tools', user: 'root', groups: 'root' }
        - { name: '/data/scripts', user: 'root', groups: 'root' }
        - { name: '/data/backups', user: 'root', groups: 'root' }
        - { name: '/data/apps', user: 'root', groups: 'root' }
        - { name: '/data/apps/redis-dump', user: 'moretv', groups: 'moretv' }
        - { name: '/data/apps/cassandra', user: 'moretv', groups: 'moretv' }
        - { name: '/data/apps/elasticsearch', user: 'moretv', groups: 'moretv' }
        - { name: '/data/apps/zookeeper', user: 'moretv', groups: 'moretv' }
        - { name: '/home/hadoop/.ssh', user: 'hadoop', groups: 'hadoop' }
        - { name: '/home/yarn/.ssh', user: 'yarn', groups: 'hadoop' }
        - { name: '/home/hdfs/.ssh', user: 'hdfs', groups: 'hadoop' }
        - { name: '/home/spark/.ssh', user: 'spark', groups: 'hadoop' }
        - { name: '/home/mesos/.ssh', user: 'mesos', groups: 'hadoop' }
        - { name: '/data/hdfs/name', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data/hdfs/journal', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data1/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data2/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data3/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data4/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data5/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data6/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data7/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data8/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data9/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data10/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data11/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data12/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data13/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data14/hdfs/data', user: 'hdfs', groups: 'hadoop' }
        - { name: '/data/yarn/timeline', user: 'yarn', groups: 'hadoop' }
        - { name: '/data1/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data2/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data3/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data4/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data5/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data6/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data7/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data8/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data9/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data10/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data11/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data12/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data13/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data14/yarn/nm-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data1/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data2/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data3/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data4/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data5/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data6/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data7/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data8/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data9/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data10/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data11/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data12/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data13/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }
        - { name: '/data14/yarn/mr-local-dir', user: 'yarn', groups: 'hadoop' }


    - name: rsync hosts
      copy: src=/data/tools/ansible/modules/ansible/config/system/hosts.sample dest=/etc/hosts owner=root group=root

    - name: rsync  /etc/profile
      copy: src=/data/tools/ansible/modules/ansible/config/system/profile.sample dest=/etc/profile

    - name: rsync /data/tools/ansible/modules/ansible/config/system to spark,moretv which use private env like JAVA_HOME
      copy: src=/data/tools/ansible/modules/ansible/config/system/bash_profile.sample dest=/home/{{ item }}/.bash_profile owner={{ item }}
      with_items:
        - spark
        - moretv

    - name: rsync /data/tools/ansible/modules/ansible/config/system to spark,moretv which use private env like JAVA_HOME
      copy: src=/data/tools/ansible/modules/ansible/config/system/hadoop_profile.sample dest=/home/{{ item }}/.bash_profile owner={{ item }} group={{ item }}
      with_items:
        - hadoop

