---
- hosts: all
  tasks:

    - name: rsync spark,hadoop known_hosts
      copy: src=/data/tools/ansible/modules/ansible/config/system/host_info/all_host dest=/home/{{ item }}/.ssh/known_hosts owner={{ item }} group=hadoop mode=0644
      tags: auth
      with_items:
        - hadoop
        - yarn
        - hdfs
        - spark
        - mesos