---
- hosts: all
  tasks:
    - name: get file
      shell: cd /tmp && rm -f sqoop-1.99.7-bin-hadoop200.tar.gz && /opt/hadoop/bin/hadoop fs -get /libs/package/sqoop-1.99.7-bin-hadoop200.tar.gz sqoop-1.99.7-bin-hadoop200.tar.gz
      tags: install
      args:
        creates: /app/sqoop-1.99.7-bin-hadoop200/.install

    - name: tar file to /app
      shell: cd /tmp && tar zxvf  sqoop-1.99.7-bin-hadoop200.tar.gz -C /app
      tags: install
      args:
        creates: /app/sqoop-1.99.7-bin-hadoop200/.install

    - name: chown
      shell: chown hadoop:hadoop -R /app/sqoop-1.99.7-bin-hadoop200

    - name: create log directory
      file: path=/data/logs/sqoop state=directory owner=hadoop group=hadoop mode=0777
      tags: install

    - name: change owner
      file: name=/app/sqoop-1.99.7-bin-hadoop200 owner=hadoop group=hadoop
      tags: install

    - name: touch install file
      shell: touch /app/sqoop-1.99.7-bin-hadoop200/.install
      tags: install
      args:
        creates: /app/sqoop-1.99.7-bin-hadoop200/.install

    - name: copy jar file
      shell: /opt/hadoop/bin/hadoop fs -get /libs/common/mysql-connector-java-5.1.39-bin.jar /app/sqoop-1.99.7-bin-hadoop200/lib
      tags: install
      args:
        creates: /app/sqoop-1.99.7-bin-hadoop200/server/lib/mysql-connector-java-5.1.39-bin.jar

    - name: copy config file
      copy: src=/data/tools/ansible/modules/sqoop/sqoop2/config/{{ item.src }} dest=/app/sqoop-1.99.7-bin-hadoop200/{{ item.dest }} owner=hadoop group=hadoop mode=755
      tags: config
      with_items:
        - { src: 'bin/sqoop.sh', dest: 'bin/sqoop.sh' }
        - { src: 'bin/sqoop2-server', dest: 'bin/sqoop2-server' }
        - { src: 'bin/sqoop2-shell', dest: 'bin/sqoop2-shell' }
        - { src: 'bin/sqoop2-tool', dest: 'bin/sqoop2-tool' }
        - { src: 'bin/sqoop-sys.sh', dest: 'bin/sqoop-sys.sh' }
        - { src: 'conf/sqoop.properties', dest: 'conf/sqoop.properties' }
        - { src: 'conf/sqoop_bootstrap.properties', dest: 'conf/sqoop_bootstrap.sh' }

    - name: create Create a soft link
      file: src=/app/sqoop-1.99.7-bin-hadoop200 dest=/opt/sqoop2 state=link owner=hadoop group=hadoop
      tags: link


