---
- hosts: all
  tasks:

    - name: create directory
      file: path={{ item }} state=directory owner=moretv group=moretv
      tags: install
      with_items:
        - /app/biserver/cis-bi

    - name: copy tar.gz file to remote host
      shell: ncftpget -z -ubigdata -p'whaley!90365' 10.255.130.6 /tmp bigdata/{{ item }}
      tags: install
      with_items:
        - cis-bi.tar.gz

    - name: decompress
      shell: cd /tmp && tar zxvf  cis-bi.tar.gz -C /app/biserver/{{ item }}
      tags: install
      args:
        creates: /app/biserver/{{ item }}/.install
      with_items:
        - cis-bi

    - name: change owner
      shell: chown -R moretv:moretv /app/biserver/
      tags: install

    - name: create Create a soft link
      file: src=/app/biserver dest=/opt/biserver state=link owner=moretv group=moretv
      tags: install

    - name: touch install file
      shell: touch /app/biserver/{{ item }}/.install
      tags: install
      args:
        creates: /app/biserver/{{ item }}/.install
      with_items:
        - cis-bi

    - name: copy config file to remote host
      copy: src=/data/tools/ansible/modules/biserver/cis-bi/config/{{ item.file }} dest=/opt/biserver/cis-bi/server/conf/{{ item.dir }} owner=moretv group=moretv mode=0644
      tags: config
      with_items:
        - { dir: '', file: 'app.properties'}
        - { dir: '', file: 'application.conf'}
        - { dir: '', file: 'application.ini'}
        - { dir: '', file: 'jdbc.properties'}
        - { dir: '', file: 'log4j.properties'}
        - { dir: '', file: 'logback.xml'}
        - { dir: '', file: 'mybatisConfig.xml'}
        - { dir: '', file: 'routes'}
