---
- hosts: all
  tasks:
    - name: copy zookeeper tar file to remote host
      copy: src=/data/tools/ansible/package/zookeeper-3.4.6.tar.gz dest=/tmp/zookeeper-3.4.6.tar.gz owner=root group=root mode=0771

    - name: tar zookeeper tar to /app
      shell: cd /tmp && tar zxvf  zookeeper-3.4.6.tar.gz -C /app

    - name: owner to zookeeper
      shell: chown -R moretv:moretv /app/zookeeper-3.4.6

    - name: /app/zookeeper-3.4.6 owner to zookeeper
      file: name=/app/zookeeper-3.4.6 owner=moretv group=moretv

    - name: create Create a soft link to zookeeper
      file: src=/app/zookeeper-3.4.6 dest=/opt/zookeeper state=link owner=moretv group=moretv

    - name: copy zookeeper config file to remote host
      copy: src=/data/tools/ansible/config/zookeeper/zoo_sample.cfg dest=/opt/zookeeper/conf/zoo.cfg owner=moretv group=moretv mode=0771

    - name: create zookeeper need directory
      file: path={{ item }}  state=directory  owner=moretv group=moretv
      with_items:
        - /opt/zookeeper/data
        - /data/logs/zookeeper


    - name: copy zookeeper config file to remote host
      copy: src=/data/tools/ansible/config/zookeeper/myid dest=/opt/zookeeper/data/myid owner=moretv group=moretv mode=0771

    - name: sync  modi conf script to desc host
      copy: src=/data/tools/ansible/scripts/modi_conf/{{ item }} dest=/data/scripts/{{ item }} owner=moretv group=moretv mode=0755
      with_items:
        - make_conf.py
        - zookeeper.conf

    - name: run modi config script
      shell: python make_conf.py zookeeper.conf
      args:
        chdir: /data/scripts