---
- hosts: all
  tasks:

    - name: create directory
      file: path={{ item }} state=directory owner=spark group=hadoop
      tags: install
      with_items:
        - /data/logs/spark212

    - name: copy spark tar file to remote host
      shell: ncftpget -z -ubigdata -p'whaley!90365' 10.255.130.6 /tmp bigdata/{{ item }}
      tags: install
      with_items:
        - spark-2.1.2-bin-hadoop2.9.0.tgz

    - name: tar spark tar to /app
      shell: cd /tmp && tar zxvf  spark-2.1.2-bin-hadoop2.9.0.tgz  -C /app
      tags: install
      args:
        creates: /app/spark-2.1.2-bin-hadoop2.9.0/.install

    - name: owner to spark
      shell: chown -R spark:hadoop /app/spark-2.1.2-bin-hadoop2.9.0
      tags: install

    - name: /app/spark-2.1.2-bin-hadoop2.9.0 owner to spark
      file: name=/app/spark-2.1.2-bin-hadoop2.9.0 owner=spark group=hadoop
      tags: install

    - name: copy spark config file to remote host
      copy: src=/data/tools/ansible/modules/spark/config/spark2.1.2_hadoop29_dev/{{ item }} dest=/app/spark-2.1.2-bin-hadoop2.9.0/conf/{{ item }} owner=spark group=hadoop mode=0771
      tags: install
      with_items:
        - spark-defaults.conf
        - spark-env.sh
        - log4j.properties
