---
- hosts: nodes
  tasks:

    - name: copy hbase tar file to remote host
      shell: ncftpget -z -ubigdata -p'whaley!90365' 10.255.130.6 /tmp bigdata/{{ item }}
      tags: install
      with_items:
        - hbase-1.2.4-bin.tar.gz

    - name: decompress hbase
      shell: cd /tmp && tar zxvf  hbase-1.2.4-bin.tar.gz -C /app
      tags: install
      args:
        creates: /app/hbase-1.2.4/.install

    - name: change owner
      shell: chown -R hadoop:hadoop /app/hbase-1.2.4
      tags: install

    - name: make dir
      file: path={{ item.name }} state=directory owner={{ item.user }} group={{ item.groups }}
      tags: install
      with_items:
        - { name: '/data/logs/hbase', user: 'hadoop', groups: 'hadoop' }

    - name: create soft link
      file: src=/app/hbase-1.2.4 dest=/opt/hbase state=link owner=hadoop group=hadoop
      tags: install

#    - name: copy phoenix jar file to remote hbase host
#      copy: src=/data/tools/ansible/modules/hbase/package/phoenix-4.10.0-HBase-1.2-server.jar dest=/opt/hbase/lib owner=hadoop group=hadoop mode=0771
#      tags: install

    - name: download file
      shell: ncftpget -z -ubigdata -p'whaley!90365' 10.255.130.6 /tmp bigdata/{{ item }}
      tags: install
      with_items:
        - phoenix-4.10.0-HBase-1.2-server.jar

    - name: change owner
      copy: path=/opt/hbase/lib/phoenix-4.10.0-HBase-1.2-server.jar state=file owner=hadoop group=hadoop mode=0771
      tags: install

    - name: touch install file
      shell: touch /app/hbase-1.2.4/.install
      tags: install
      args:
        creates: /app/hbase-1.2.4/.install

    - name: create soft link core-site.xml of hadoop config to hbase config dir
      file: src=/opt/hadoop/etc/hadoop/core-site.xml dest=/opt/hbase/conf/core-site.xml state=link owner=hadoop group=hadoop
      tags: config

    - name: create soft link hdfs-site.xml of hadoop config to hbase config dir
      file: src=/opt/hadoop/etc/hadoop/hdfs-site.xml dest=/opt/hbase/conf/hdfs-site.xml state=link owner=hadoop group=hadoop
      tags: config

    - name: create soft link hdfs-site.xml of hadoop config to hbase config dir
      file: src=/app/apache-phoenix-4.10.0-HBase-1.2-bin/phoenix-4.10.0-HBase-1.2-server.jar dest=/opt/hbase/lib/phoenix-hbase-server.jar state=link owner=hadoop group=hadoop
      tags: config

    - name: copy hbase config file to remote host
      copy: src=/data/tools/ansible/modules/hbase/config_test/etc/hbase/{{ item.name }} dest={{ item.dest }} owner=hadoop group=hadoop mode=755
      tags: config
      with_items:
        - {name: 'backup-masters', dest: '/opt/hbase/conf'}
        - {name: 'hbase-env.sh', dest: '/opt/hbase/conf'}
        - {name: 'hbase-site.xml', dest: '/opt/hbase/conf'}
        - {name: 'regionservers', dest: '/opt/hbase/conf'}
        - {name: 'log4j.properties', dest: '/opt/hbase/conf'}
        - {name: 'monitor_hbase.sh', dest: '/opt/hbase/conf'}
        - {name: 'hadoop-metrics2-hbase.properties', dest: '/opt/hbase/conf'}
    - name: change chmod
      shell: chmod 777 -R /data/logs/hbase
      tags: change_chmod
