---
- hosts: all
  tasks:

    - name: rsync iptables scripts
      copy: src=/data/tools/ansible/modules/ansible/scripts/iptables/iptables_extsrv_collect01.sh dest=/data/tools/iptables.sh owner=root group=root mode=0755
      tags: config

    - name : run iptables script
      command : sh /data/tools/iptables.sh
      tags: config

    - name : iptable-save
      command : iptables-save
      tags: config

    - name: run iptables rule in system restart
      shell:  echo "sh /data/tools/iptables.sh " >>/etc/rc.d/rc.local
      tags: install
      args:
        creates: /data/tools/.iptables

    - name: touch install file
      shell: touch /data/tools/.iptables
      tags: install
      args:
        creates: /data/tools/.iptables