---
- hosts: all
  tasks:
    - name: get file
      shell: cd /tmp && rm -f /tmp/apache-phoenix-4.8.2-HBase-1.2-bin.tar.gz && /opt/hadoop/bin/hadoop fs -get /libs/package/apache-phoenix-4.8.2-HBase-1.2-bin.tar.gz
      tags: install
      args:
        creates: /app/apache-phoenix-4.8.2-HBase-1.2-bin/.install

    - name: tar file to /app
      shell: cd /tmp && tar zxvf  apache-phoenix-4.8.2-HBase-1.2-bin.tar.gz -C /app
      tags: install
      args:
        creates: /app/apache-phoenix-4.8.2-HBase-1.2-bin/.install

    - name: create log directory
      file: path=/data/logs/phoenix state=directory owner=hadoop group=hadoop mode=0777
      tags: install

    - name: change owner
      file: name=/app/apache-phoenix-4.8.2-HBase-1.2-bin owner=hadoop group=hadoop
      tags: install

    - name: touch install file
      shell: touch /app/apache-phoenix-4.8.2-HBase-1.2-bin/.install
      tags: install
      args:
        creates: /app/apache-phoenix-4.8.2-HBase-1.2-bin/.install

    - name: copy config file
      copy: src=/data/tools/ansible/modules/phoenix/config/{{ item.src }} dest=/app/apache-phoenix-4.8.2-HBase-1.2-bin/{{ item.dest }} owner=hadoop group=hadoop mode=755
      tags: config
      with_items:
        - {src: 'bin/log4j.properties' , dest: 'bin/log4j.properties'}
        - {src: 'bin/tephra-env.sh' , dest: 'bin/tephra-env.sh'}
        - {src: 'bin/config/log4j.properties' , dest: 'bin/config/log4j.properties'}
        - {src: 'bin/config/pherf.properties' , dest: 'bin/config/pherf.properties'}
        - {src: 'bin/config/env.sh' , dest: 'bin/config/env.sh'}

    - name: Create a soft link
      file: src=/app/apache-phoenix-4.8.2-HBase-1.2-bin dest=/opt/phoenix state=link owner=hadoop group=hadoop
      tags: link

    - name: create a soft link to hbase
      file: src=/app/apache-phoenix-4.8.2-HBase-1.2-bin/phoenix-4.8.2-HBase-1.2-server.jar dest=/opt/hbase/lib/phoenix-hbase-server.jar  state=link owner=hadoop group=hadoop
      tags: link

    - name: create a soft link from hbase
      file: src=/opt/hbase/conf/{{ item.src }} dest=/app/apache-phoenix-4.8.2-HBase-1.2-bin/bin/{{ item.dest }} state=link owner=hadoop group=hadoop
      tags: link
      with_items:
          - {src: 'hbase-env.sh' , dest: 'hbase-env.sh'}
          - {src: 'hbase-site.xml' , dest: 'hbase-site.xml'}


    - name: create a soft link for hive
      file: src=/app/apache-phoenix-4.8.2-HBase-1.2-bin/{{ item.src }} dest=/opt/hive/lib/{{ item.dest }} state=link owner=hadoop group=hadoop
      tags: link
      with_items:
          - {src: 'phoenix-hive-4.8.2-HBase-1.2.jar' , dest: 'phoenix-hive-HBase.jar'}
          - {src: 'phoenix-hive-4.8.2-HBase-1.2-sources.jar' , dest: 'phoenix-hive-HBase-sources.jar'}
          - {src: 'phoenix-4.8.2-HBase-1.2-server.jar' , dest: 'phoenix-HBase-server.jar'}

