---
- hosts: all
  tasks:
    - name: copy tar file to remote host
      copy: src=/data/tools/ansible/modules/phoenix/package/apache-phoenix-4.10.0-HBase-1.2-bin.tar.gz dest=/tmp/apache-phoenix-4.10.0-HBase-1.2-bin.tar.gz owner=hadoop group=hadoop mode=0771
      tags: install

    - name: tar file to /app
      shell: cd /tmp && tar zxvf apache-phoenix-4.10.0-HBase-1.2-bin.tar.gz -C /app
      tags: install
      args:
        creates: /app/apache-phoenix-4.10.0-HBase-1.2-bin/.install

    - name: create log directory
      file: path=/data/logs/phoenix state=directory owner=hadoop group=hadoop mode=0777
      tags: install

    - name: change owner
      file: name=/app/apache-phoenix-4.10.0-HBase-1.2-bin owner=hadoop group=hadoop
      tags: install

    - name: touch install file
      shell: touch /app/apache-phoenix-4.10.0-HBase-1.2-bin/.install
      tags: install
      args:
        creates: /app/apache-phoenix-4.10.0-HBase-1.2-bin/.install

    - name: copy config file
      copy: src=/data/tools/ansible/modules/phoenix/config_test/{{ item.src }} dest=/app/apache-phoenix-4.10.0-HBase-1.2-bin/{{ item.dest }} owner=hadoop group=hadoop mode=755
      tags: config
      with_items:
        - {src: 'bin/log4j.properties' , dest: 'bin/log4j.properties'}
        - {src: 'bin/tephra-env.sh' , dest: 'bin/tephra-env.sh'}
        - {src: 'bin/config/log4j.properties' , dest: 'bin/config/log4j.properties'}
        - {src: 'bin/config/pherf.properties' , dest: 'bin/config/pherf.properties'}
        - {src: 'bin/config/env.sh' , dest: 'bin/config/env.sh'}

    - name: updatejar
      copy: src=/data/tools/ansible/modules/phoenix/package/{{ item.src }} dest=/app/apache-phoenix-4.10.0-HBase-1.2-bin/{{ item.dest }} owner=hadoop group=hadoop mode=755
      tags: updatejar
      with_items:
        - {src: 'phoenix-hive-4.10.0-HBase-1.2.jar' , dest: 'phoenix-hive-4.10.0-HBase-1.2.jar'}
        - {src: 'phoenix-hive-4.10.0-HBase-1.2-sources.jar' , dest: 'phoenix-hive-4.10.0-HBase-1.2-sources.jar'}

    - name: Create a soft link
      file: src=/app/apache-phoenix-4.10.0-HBase-1.2-bin dest=/opt/phoenix state=link owner=hadoop group=hadoop
      tags: link

    - name: create a soft link from hbase
      file: src=/opt/hbase/conf/{{ item.src }} dest=/app/apache-phoenix-4.10.0-HBase-1.2-bin/bin/{{ item.dest }} state=link owner=hadoop group=hadoop
      tags: link
      with_items:
          - {src: 'hbase-env.sh' , dest: 'hbase-env.sh'}
          - {src: 'hbase-site.xml' , dest: 'hbase-site.xml'}

    - name: create directory /opt/hive/lib/
      file: path=/opt/hive/lib/ state=directory owner=hadoop group=hadoop mode=0777
      tags: link

    - name: create a soft link for hive
      file: src=/app/apache-phoenix-4.10.0-HBase-1.2-bin/{{ item.src }} dest=/opt/hive/lib/{{ item.dest }} state=link owner=hadoop group=hadoop
      tags: link
      with_items:
          - {src: 'phoenix-hive-4.10.0-HBase-1.2.jar' , dest: 'phoenix-hive-HBase.jar'}
          - {src: 'phoenix-hive-4.10.0-HBase-1.2-sources.jar' , dest: 'phoenix-hive-HBase-sources.jar'}
          - {src: 'phoenix-4.10.0-HBase-1.2-server.jar' , dest: 'phoenix-HBase-server.jar'}

    - name: rm old tmp
      shell: rm /app/apache-phoenix-4.10.0-HBase-1.2-bin/bin/hbase-site.xml
      tags: rmold
    - name: change owner tmp
      file: dest=/app/apache-phoenix-4.10.0-HBase-1.2-bin owner=hadoop group=hadoop mode=0775 recurse=yes
      tags: change_owner_tmp