---
- hosts: all
  tasks:
    - name: create gaoshen_cdn  directory
      file: path={{ item }} state=directory owner=hadoop group=hadoop
      tags: install
      with_items:
        - /data/logs/gaoshen_cdn
        - /app/gaoshen_cdn

    - name: copy gaoshen_cdn tar file to remote host
      shell: ncftpget -z -ubigdata -p'whaley!90365' 10.255.130.6 /tmp bigdata/{{ item }}
      tags: install
      with_items:
        - gaoshen_cdn-exec-server-3.0.tar.gz

    - name: tar gaoshen_cdn tar to /app/gaoshen_cdn
      shell: cd /tmp && tar -zxvf  gaoshen_cdn-exec-server-3.0.tar.gz -C /app/gaoshen_cdn
      args:
        creates: /app/gaoshen_cdn/gaoshen_cdn-exec-server-3.0/.install

    - name: owner to hadoop
      shell: chown -R hadoop:hadoop /app/gaoshen_cdn/gaoshen_cdn-exec-server-3.0
      args:
        creates: /app/gaoshen_cdn/gaoshen_cdn-exec-server-3.0/.install

    - name: /app/gaoshen_cdn owner to hadoop
      file: name=/app/gaoshen_cdn owner=hadoop group=hadoop

    - name: create a soft link to gaoshen_cdn
      file: src=/app/gaoshen_cdn dest=/opt/gaoshen_cdn state=link owner=hadoop group=hadoop

    - name: touch install file
      shell: touch /app/gaoshen_cdn/gaoshen_cdn-exec-server-3.0/.install
      tags: install
      args:
        creates: /app/gaoshen_cdn/gaoshen_cdn-exec-server-3.0/.install

    - name: copy gaoshen_cdn config file to remote host
      copy: src=/data/tools/ansible/modules/gaoshen_cdn/config_server/{{ item }} dest=/opt/gaoshen_cdn/gaoshen_cdn-exec-server-3.0/conf/{{ item }} owner=hadoop group=hadoop mode=0771
      with_items:
        - gaoshen_cdn.properties
        - global.properties
        - log4j.properties
        - execute-as-user
    - name: copy gaoshen_cdn config file to remote host
      copy: src=/data/tools/ansible/modules/gaoshen_cdn/config_server/{{ item }} dest=/opt/gaoshen_cdn/gaoshen_cdn-exec-server-3.0/plugins/jobtypes/{{ item }} owner=hadoop group=hadoop mode=0771
      with_items:
        - commonprivate.properties




