---
- hosts: nodes
  tasks:
  - name: copy logstash config file to remote host
    copy: src=/data/tools/ansible/modules/logstash_v5/config/etc/logstash/{{ item.name }} dest={{ item.dest }} owner=moretv group=moretv mode=755
    tags: business_config
    with_items:
     - {name: 'kafka_topic_distribute_medusa_player_sdk_startplay.conf',              dest: '/opt/logstash_v5/config'}
     - {name: 'kafka_topic_distribute_helios_player_sdk_startplay.conf',              dest: '/opt/logstash_v5/config'}
     - {name: 'kafka_topic_distribute_player_sdk_startplay_merge.conf',               dest: '/opt/logstash_v5/config'}
     - {name: 'kafka_es.conf',                                                        dest: '/opt/logstash_v5/config'}
     - {name: 'activity-template.json',                                               dest: '/opt/logstash_v5/config'}