---
- hosts: all
  tasks:
    - name: get file
      shell: ncftpget -z -ubigdata -p'whaley!90365' 10.255.130.6 /tmp bigdata/{{ item }}
      tags: install
      with_items:
        - apache-hive-2.1.1-bin.tar.gz

    - name: tar file to /app
      shell: cd /tmp && tar zxvf  apache-hive-2.1.1-bin.tar.gz -C /app
      tags: install
      args:
        creates: /app/apache-hive-2.1.1-bin/.install

    - name: create log directory
      file: path=/data/logs/hive state=directory owner=hadoop group=hadoop mode=0777
      tags: install

    - name: change owner
      file: name=/app/apache-hive-2.1.1-bin owner=hadoop group=hadoop
      tags: install

    - name: touch install file
      shell: touch /app/apache-hive-2.1.1-bin/.install
      tags: install
      args:
        creates: /app/apache-hive-2.1.1-bin/.install

    - name: copy jar file to remote host
      copy: src=/data/tools/ansible/modules/hive/config/{{ item }} dest=/app/apache-hive-2.1.1-bin/lib/{{ item }} owner=hadoop group=hadoop mode=0771
      tags: config
      with_items:
          - mysql-connector-java-5.1.39-bin.jar

    - name: copy config file
      copy: src=/data/tools/ansible/modules/hive/config/{{ item }} dest=/app/apache-hive-2.1.1-bin/conf/{{ item }} owner=hadoop group=hadoop mode=755
      tags: config
      with_items:
        - hive-env.sh
        - hive-default.xml
        - hive-site.xml
        - hive-log4j2.properties
        - hive-exec-log4j2.properties
        - hive-monitor.sh
        - ivysettings.xml
        - beeline-log4j2.properties
        - llap-cli-log4j2.properties
        - llap-daemon-log4j2.properties
        - parquet-logging.properties

    - name: create Create a soft link
      file: src=/app/apache-hive-2.1.1-bin dest=/opt/hive state=link owner=hadoop group=hadoop
      tags: link

    - name: create a soft link to hcatalog for hive
      file: src=/app/apache-hive-2.1.1-bin/hcatalog/share/hcatalog/{{item.src}} dest=/opt/hive/lib/{{item.dest}} state=link owner=hadoop group=hadoop
      tags: link
      with_items:
        - { src: 'hive-hcatalog-core-2.1.1.jar', dest: 'hive-hcatalog-core.jar'}
        - { src: 'hive-hcatalog-pig-adapter-2.1.1.jar', dest: 'hive-hcatalog-pig-adapter.jar'}
        - { src: 'hive-hcatalog-server-extensions-2.1.1.jar', dest: 'hive-hcatalog-server-extensions.jar'}
        - { src: 'hive-hcatalog-streaming-2.1.1.jar', dest: 'hive-hcatalog-streaming.jar'}


    - name: download jar file
      shell: ncftpget -z -ubigdata -p'whaley!90365' 10.255.130.6 /tmp bigdata/{{ item }}
      tags: updatejar
      with_items:
        - hive-exec-2.1.1.jar

    - name: change mode jar file
      file: path=/app/apache-hive-2.1.1-bin/lib/{{ item }} state=file owner=hadoop group=hadoop mode=755
      tags: updatejar
      with_items:
        - hive-exec-2.1.1.jar

    - name: update jar file
      copy: src=/data/tools/ansible/modules/hive/package/{{ item }} dest=/app/apache-hive-2.1.1-bin/hcatalog/share/hcatalog/{{ item }} owner=hadoop group=hadoop mode=755
      tags: updatejar-hcatalog
      with_items:
        - hive-hcatalog-core-2.1.1.jar