---
- hosts: all
  tasks:
    - name: create hive log directory
      file: path=/data/logs/hive state=directory owner=hadoop group=hadoop
    
    - name: copy hive tar file to remote host
      shell: ncftpget -z -ubigdata -p'whaley!90365' 10.255.130.6 /tmp bigdata/{{ item }}
      tags: install
      with_items:
        - apache-hive-1.2.1-bin.tar.gz

    - name: tar hive tar to /app
      shell: cd /tmp && tar zxvf  apache-hive-1.2.1-bin.tar.gz -C /app
      args:
        creates: /app/apache-hive-1.2.1-bin/.install

    - name: owner to hadoop
      shell: chown -R hadoop:hadoop /app/apache-hive-1.2.1-bin

    - name: /app/hive owner to hadoop
      file: name=/app/apache-hive-1.2.1-bin owner=hadoop group=hadoop

    - name: create Create a soft link to hive
      file: src=/app/apache-hive-1.2.1-bin dest=/opt/hive state=link owner=hadoop group=hadoop

    - name: touch install file
      shell: touch /app/apache-hive-1.2.1-bin/.install
      tags: install
      args:
        creates: /app/apache-hive-1.2.1-bin/.install

    - name: copy hive config file to remote host
      copy: src=/data/tools/ansible/modules/hive/config/{{ item }} dest=/opt/hive/conf/{{ item }} owner=hadoop group=hadoop mode=0771
      tags: config
      with_items:
        - hive-env.sh
        - hive-site.xml
        - hive-log4j.properties
        - hive-exec-log4j.properties
        - hive-monitor.sh
        - ivysettings.xml
        - beeline-log4j.properties

    - name: copy hive mysql-connector-java-5.1.39-bin.jar file to remote host
      copy: src=/data/tools/ansible/modules/hive/config/{{ item }} dest=/opt/hive/lib/{{ item }} owner=hadoop group=hadoop mode=0771
      with_items:
          - mysql-connector-java-5.1.39-bin.jar


