---
- hosts: all
  tasks:

    - name: rsync yunwei_init scripts
      copy: src=/data/tools/ansible/modules/ULB/config/ifcfg-ulb03 dest=/etc/sysconfig/network-scripts/ifcfg-lo:3 owner=root group=root mode=0644
      tags: ulb

    - name : run  script
      command : ifup lo:3
      tags: ulb