---
- hosts: all
  tasks:

    - name: create directory
      file: path={{ item }} state=directory owner=hadoop group=hadoop
      tags: install
      with_items:
        - /app/zeppelin-0.7.2-bin-all
        - /app/zeppelin-0.7.2-bin-all-rom

    - name: download tgz
      shell: ncftpget -z -ubigdata -p'whaley!90365' 10.255.130.6 /tmp bigdata/{{ item }}
      tags: install
      with_items:
        - zeppelin-0.7.2-bin-all.tgz
        - rom_notebook.tgz
        - bigdata_notebook.tgz

    - name: decompress
      shell: cd /tmp && tar zxvf  zeppelin-0.7.2-bin-all.tgz -C /app/{{ item }}
      tags: install
      args:
        creates: /app/{{ item }}/.install
      with_items:
        - zeppelin-0.7.2-bin-all
        - zeppelin-0.7.2-bin-all-rom

    - name: decompress
      shell: cd /tmp && tar zxvf  rom_notebook.tgz -C /app/{{ item }}
      tags: install
      args:
        creates: /app/{{ item }}/.install
      with_items:
        - zeppelin-0.7.2-bin-all-rom

    - name: decompress
      shell: cd /tmp && tar zxvf  bigdata_notebook.tgz -C /app/{{ item }}
      tags: install
      args:
        creates: /app/{{ item }}/.install
      with_items:
        - zeppelin-0.7.2-bin-all

    - name: change owner
      shell: chown -R hadoop:hadoop /app/{{ item }}
      tags: install
      with_items:
        - zeppelin-0.7.2-bin-all
        - zeppelin-0.7.2-bin-all-rom

    - name: create Create a soft link to spark
      file: src=/app/{{ item.src }} dest=/opt/{{ item.dest }} state=link owner=hadoop group=hadoop
      tags: install
      with_items:
        - { src: 'zeppelin-0.7.2-bin-all', dest: 'zeppelin2'}
        - { src: 'zeppelin-0.7.2-bin-all-rom', dest: 'zeppelin-rom2'}

    - name: touch install file
      shell: touch /app/{{ item }}/.install
      tags: install
      args:
        creates: /app/{{ item }}/.install
      with_items:
        - zeppelin-0.7.2-bin-all
        - zeppelin-0.7.2-bin-all-rom

    - name: copy config file to remote host
      copy: src=/data/tools/ansible/modules/zeppelin/config/{{ item.src }} dest=/opt/{{item.dest}} owner=hadoop group=hadoop mode=0771
      tags: config
      with_items:
        - { src: 'bigdata/zeppelin-env.sh', dest: 'zeppelin2/conf/zeppelin-env.sh'}
        - { src: 'bigdata/zeppelin-site.xml', dest: 'zeppelin2/conf/zeppelin-site.xml'}
        - { src: 'bigdata/shiro.ini', dest: 'zeppelin2/conf/shiro.ini'}
        - { src: 'rom/zeppelin-env.sh', dest: 'zeppelin-rom2/conf/zeppelin-env.sh'}
        - { src: 'rom/zeppelin-site.xml', dest: 'zeppelin-rom2/conf/zeppelin-site.xml'}
        - { src: 'rom/shiro.ini', dest: 'zeppelin-rom2/conf/shiro.ini'}

    - name: sync  modi conf script to desc host
      copy: src=/data/tools/ansible/modules/ansible/scripts/modi_conf/{{ item }} dest=/data/scripts/{{ item }} owner=hadoop group=hadoop mode=0755
      tags: config
      with_items:
        - make_conf.py
        - zeppelin.conf

    - name: run modi config script
      shell: python make_conf.py zeppelin.conf
      tags: config
      args:
        chdir: /data/scripts

