---
- hosts: tez-ui
  tasks:

    - name: create log directory
      file: path=/data/logs/tomcat state=directory owner=hadoop group=hadoop

    - name: copy tar file to remote host
      tags: install
      copy: src=/data/tools/ansible/modules/hive/package/apache-tomcat-8.0.28.tar.gz dest=/tmp owner=hadoop group=hadoop mode=0771

    - name: tar to /app
      shell: cd /tmp && tar zxvf  apache-tomcat-8.0.28.tar.gz -C /app
      tags: install
      args:
        creates: /app/apache-tomcat-8.0.28/.install

    - name: owner to hadoop
      tags: install
      shell: chown -R hadoop:hadoop /app/apache-tomcat-8.0.28

    - name: chown to hadoop
      tags: install
      file: name=/app/apache-tomcat-8.0.28 owner=hadoop group=hadoop

    - name: create a soft link
      tags: install
      file: src=/app/apache-tomcat-8.0.28 dest=/opt/tomcat state=link owner=hadoop group=hadoop

    - name: touch install file
      shell: touch /app/apache-tomcat-8.0.28/.install
      tags: install
      args:
        creates: /app/apache-tomcat-8.0.28/.install

    - name: copy config file
      copy: src=/data/tools/ansible/modules/hive/config/{{ item.name }} dest=/app/apache-tomcat-8.0.28/{{ item.dest }} owner=hadoop group=hadoop mode=0771
      tags: config
      with_items:
        - {name: 'tomcat/conf/server.xml', dest: 'conf'}
        - {name: 'tomcat/conf/web.xml', dest: 'conf'}
        - {name: 'tomcat/conf/logging.properties', dest: 'conf'}

    - name: create a soft link
      tags: install
      file: src=/opt/tez/tez-ui2-0.8.4.war dest=/app/apache-tomcat-8.0.28/webapps/tez-ui.war state=link owner=hadoop group=hadoop

