---
- hosts: all
  tasks:

    - name: create directory
      file: path={{ item.name }} state=directory owner={{ item.user }} group={{ item.groups }}   
      with_items: 

        - { name: '/data', user: 'moretv', groups: 'moretv', mode: '0755' }
        - { name: '/data/logs', user: 'moretv', groups: 'moretv', mode: '0755' }
        - { name: '/data/tools', user: 'root', groups: 'root', mode: '0755' }
        - { name: '/data/scripts', user: 'root', groups: 'root', mode: '0755' }
        - { name: '/data/backups', user: 'root', groups: 'root', mode: '0755' }
        - { name: '/data/hdfs/name', user: 'hdfs', groups: 'hadoop', mode: '0755' }
        - { name: '/data/hdfs/journal', user: 'hdfs', groups: 'hadoop', mode: '0755' }
        - { name: '/data/yarn/timeline', user: 'yarn', groups: 'hadoop', mode: '0755' }
        - { name: '/data/bak', user: 'moretv', groups: 'moretv', mode: '0755' }
        - { name: '/data/local_backups/old_back', user: 'root', groups: 'root', mode: '0755' }
        - { name: '/data/webapps', user: 'moretv', groups: 'moretv' }
        - { name: '/data/logs', user: 'moretv', groups: 'moretv', mode: '0755'}
        - { name: '/data/logs/filebeat_v5', user: 'moretv', groups: 'moretv', mode: '0755' }
        - { name: '/data/logs/hadoop-hdfs', user: 'hadoop', groups: 'hadoop', mode: '0755' }
        - { name: '/data/logs/hadoop-yarn', user: 'hadoop', groups: 'hadoop', mode: '0755' }
        - { name: '/data/logs/hive', user: 'hadoop', groups: 'hadoop' , mode: '0777' }
        - { name: '/data/logs/nginx', user: 'nobody', groups: 'nobody', mode: '0755' }
        - { name: '/data/logs/nginx-upload', user: 'root', groups: 'root' }

    - name: chmod 777 to hive
      shell: chmod 777 /data/logs/hive

    - name: sync hive file
      copy: src=/data/tools/ansible/modules/log-scripts/host_init/hive dest=/opt/hive/bin/hive owner=hadoop group=hadoop mode=0755