---
- hosts: all
  tasks:
    - name: copy kafka tar file to remote host
      shell: ncftpget -z -ubigdata -p'whaley!90365' 10.255.130.6 /tmp bigdata/{{ item }}
      with_items:
        - kafka1_2.10-0.8.2.2.tar.gz

    - name: tar kafka tar to /app
      shell: cd /tmp && tar zxvf  kafka1_2.10-0.8.2.2.tar.gz -C /app
      args:
        creates: /app/kafka1_2.10-0.8.2.2/.install

    - name: owner to kafka
      shell: chown -R moretv:moretv /app/kafka1_2.10-0.8.2.2

      
    - name: /app/kafka_2.10-0.8.2.2 owner to kafka1
      file: name=/app/kafka1_2.10-0.8.2.2 owner=moretv group=moretv

    - name: create Create a soft link to kafka
      file: src=/app/kafka1_2.10-0.8.2.2 dest=/opt/kafka1 state=link owner=moretv group=moretv

    - name: copy kafka config file to remote host
      copy: src=/data/tools/ansible/modules/kafka/config/kafka1.properties dest=/opt/kafka1/config/server.properties owner=moretv group=moretv mode=0771

    - name: create kafka need directory
      file: path={{ item }}  state=directory  owner=moretv group=moretv
      with_items:
        - /data/logs/kafka1

    - name: sync  modi conf script to desc host
      copy: src=/data/tools/ansible/modules/ansible/scripts/modi_conf/{{ item }} dest=/data/scripts/{{ item }} owner=moretv group=moretv mode=0755
      with_items:
        - make_conf.py
        - kafka_test.conf



    - name: run modi config script
      shell: python make_conf.py kafka_test.conf
      args:
        chdir: /data/scripts

    - name: touch install file
      shell: touch /app/kafka1_2.10-0.8.2.2/.install
      tags: install
      args:
        creates: /app/kafka1_2.10-0.8.2.2/.install
