---
- hosts: all
  tasks:

    - name: create kafka_topic_distribute_helios_hot_16 cron
      cron: name="forest autostart job 1" minute=*/6 user="moretv" job="sh /opt/forest-bi/Forest-1.0.0-SNAPSHOT-bin/bin/helios_product_start.sh >/dev/null 2>&1"

    - name: create start_filebeat_helios_raw_log.sh  cron
      cron: name="forest autostart job 2" minute=*/6 user="moretv" job="sh /opt/forest-bi/Forest-1.0.0-SNAPSHOT-bin/bin/medusa_product_start.sh >/dev/null 2>&1"

    - name: create kafka_topic_distribute_helios_hot_16 cron
      cron: name="forest autostart job 3" minute=*/6 user="moretv" job="sh /opt/forest-bi/Forest-1.0.0-SNAPSHOT-bin/bin/whaley_thorprobe_start.sh >/dev/null 2>&1"
