---
- hosts: all
  tasks:
    - name: rsync init scripts
      copy: src=/data/tools/ansible/modules/nginx/package/openresty-1.11.2.5.tar.gz dest=/tmp owner=root group=root mode=0755

    - name : run init script
      shell : tar zxvf  openresty-1.11.2.5.tar.gz -C /tmp
      args:
        chdir: /tmp
        creates: /app/openresty-1.11.2.5/.install

    - name: install package from yum repo
      yum: name={{ item }}  state=present
      with_items:
        - readline-devel
        - pcre-devel
        - openssl-devel

    - name : configure
      shell : ./configure --prefix=/app/openresty-1.11.2.5    --with-luajit   --without-http_redis2_module    --with-http_iconv_module    --with-http_stub_status_module  --with-stream
      args:
        chdir: /tmp/openresty-1.11.2.5
        creates: /app/openresty-1.11.2.5/.install

    - name : make & make install
      shell : make -j2 && make install
      args:
        chdir: /tmp/openresty-1.11.2.5
        creates: /app/openresty-1.11.2.5/.install

    - name : add nginx with system restart
      shell : echo "cd /opt/openresty/nginx/sbin && ./nginx" >> /etc/rc.local
      args:
        creates: /app/openresty-1.11.2.5/.install

    - name: create  a soft link to nginx
      file: src=/app/openresty-1.11.2.5 dest=/opt/openresty state=link owner=root group=root