---
- hosts: all
  tasks:

    - name: create directory
      file: path={{ item }} state=directory owner=moretv group=moretv
      tags: install
      with_items:
        - /app/biserver/apache-tomcat-openbi

    - name: copy tar.gz file to remote host
      shell: ncftpget -z -ubigdata -p'whaley!90365' 10.255.130.6 /tmp bigdata/{{ item }}
      tags: install
      with_items:
        - apache-tomcat-openbi.tar.gz

    - name: decompress
      shell: cd /tmp && tar zxvf  apache-tomcat-openbi.tar.gz -C /app/biserver/{{ item }}
      tags: install
      args:
        creates: /app/biserver/{{ item }}/.install
      with_items:
        - apache-tomcat-openbi

    - name: change owner
      shell: chown -R moretv:moretv /app/biserver/
      tags: install

    - name: create Create a soft link
      file: src=/app/biserver dest=/opt/biserver state=link owner=moretv group=moretv
      tags: install

    - name: touch install file
      shell: touch /app/biserver/{{ item }}/.install
      tags: install
      args:
        creates: /app/biserver/{{ item }}/.install
      with_items:
        - apache-tomcat-openbi

    - name: copy config file to remote host
      copy: src=/data/tools/ansible/modules/biserver/apache-tomcat-openbi/config/{{ item.file }} dest=/opt/biserver/apache-tomcat-openbi/{{ item.dir }} owner=moretv group=moretv mode=0644
      tags: config
      with_items:
        - { dir: 'conf', file: 'server.xml'}
        - { dir: 'webapps/openBI/WEB-INF/classes', file: 'sqlMapConfig.xml'}
