---
authenticator: AllowAllAuthenticator
authorizer: AllowAllAuthorizer
auto_snapshot: true
batch_size_fail_threshold_in_kb: 50
batch_size_warn_threshold_in_kb: 5
batchlog_replay_throttle_in_kb: 1024
cas_contention_timeout_in_ms: 1000
client_encryption_options:
  enabled: false
  keystore: conf/.keystore
  keystore_password: cassandra
  optional: false
cluster_name: {{cluster_name}}
column_index_size_in_kb: 64
commit_failure_policy: stop
commitlog_directory: {{commitlog_directory}}
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
compaction_large_partition_warning_threshold_mb: 100
compaction_throughput_mb_per_sec: 16
concurrent_counter_writes: 32
concurrent_materialized_view_writes: 32
concurrent_reads: 32
concurrent_writes: 32
counter_cache_save_period: 7200
counter_cache_size_in_mb: ~
counter_write_request_timeout_in_ms: 5000
credentials_validity_in_ms: 2000
cross_node_timeout: false
data_file_directories:
  - {{data_file_directories}}
disk_failure_policy: stop
dynamic_snitch_badness_threshold: 0.1
dynamic_snitch_reset_interval_in_ms: 600000
dynamic_snitch_update_interval_in_ms: 100
enable_scripted_user_defined_functions: false
enable_user_defined_functions: false
endpoint_snitch: SimpleSnitch
gc_warn_threshold_in_ms: 1000
hinted_handoff_enabled: true
hinted_handoff_throttle_in_kb: 1024
hints_flush_period_in_ms: 10000
incremental_backups: false
index_summary_capacity_in_mb: ~
index_summary_resize_interval_in_minutes: 60
inter_dc_tcp_nodelay: false
internode_compression: all
key_cache_save_period: 14400
key_cache_size_in_mb: ~
listen_address: {{listen_address}}
max_hint_window_in_ms: 10800000
max_hints_delivery_threads: 2
max_hints_file_size_in_mb: 128
memtable_allocation_type: heap_buffers
native_transport_port: 9042
num_tokens: 256
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
permissions_validity_in_ms: 2000
range_request_timeout_in_ms: 10000
read_request_timeout_in_ms: 20000
request_scheduler: org.apache.cassandra.scheduler.NoScheduler
request_timeout_in_ms: 10000
role_manager: CassandraRoleManager
roles_validity_in_ms: 2000
row_cache_save_period: 0
row_cache_size_in_mb: 0
rpc_address: {{rpc_address}}
rpc_keepalive: true
rpc_port: 9160
rpc_server_type: sync
seed_provider:
  -
    class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
      -
        seeds: {{seeds}}
server_encryption_options:
  internode_encryption: none
  keystore: conf/.keystore
  keystore_password: cassandra
  truststore: conf/.truststore
  truststore_password: cassandra
snapshot_before_compaction: false
ssl_storage_port: 7001
sstable_preemptive_open_interval_in_mb: 50
start_native_transport: true
start_rpc: false
storage_port: 7000
thrift_framed_transport_size_in_mb: 15
tombstone_failure_threshold: 100000
tombstone_warn_threshold: 1000
tracetype_query_ttl: 86400
tracetype_repair_ttl: 604800
transparent_data_encryption_options:
  chunk_length_kb: 64
  cipher: AES/CBC/PKCS5Padding
  enabled: false
  key_alias: "testing:1"
  key_provider:
    -
      class_name: org.apache.cassandra.security.JKSKeyProvider
      parameters:
        -
          key_password: cassandra
          keystore: conf/.keystore
          keystore_password: cassandra
          store_type: JCEKS
trickle_fsync: false
trickle_fsync_interval_in_kb: 10240
truncate_request_timeout_in_ms: 60000
windows_timer_interval: 1
write_request_timeout_in_ms: 10000
