---
- hosts: all
  tasks:
    - name: create guessyoulike directory
      file: path={{ item }} state=directory owner=spark group=hadoop
      tags: install
      with_items:
        - /app/ai/config
    
    - name: copy package to remote host
      copy: src=/data/tools/ansible/modules/recommand-scripts/hdfsconfig/package/aisdk-config2.10_1.0.6.json dest=/app/ai/config owner=spark group=hadoop mode=0771
      tags: install

    - name: copy package to remote host
      copy: src=/data/tools/ansible/modules/recommand-scripts/hdfsconfig/package/aisdk-config2.11_1.0.6.json dest=/app/ai/config owner=spark group=hadoop mode=0771
      tags: install

    - name: decompress package
      shell: chown -R spark:hadoop /app/ai/config
      tags: install

    - name: create a soft link
      file: src=/app/ai/config dest=/opt/ai/config state=link owner=spark group=hadoop
      tags: install



